<div class="message success countdown"><?php echo $block->buildString(); ?></div>
<script>
function startTimer(duration, display) {
	var timer = duration;
	setInterval(function () {
		time = new Date(timer * 1000).toISOString().substr(11, 8);
		display.textContent = time;
		if (--timer < 0) {
			timer = 86400;
			var date = new Date(document.getElementById('date').innerHTML);
			date.setDate(date.getDate() + 1);
			var dd = today.getDate();
			var mm = today.getMonth()+1; //January is 0!
			var yyyy = today.getFullYear();
			if(dd<10){
				dd='0'+dd;
			} 
			if(mm<10){
				mm='0'+mm;
			}
			var date = dd+'/'+mm+'/'+yyyy;
			
			document.getElementById('date').innerHTML = date;
		}
	}, 1000);
}

window.onload = function () {
	var time = <?php echo $block->getTimeRemainingSeconds(); ?>,
		display = document.querySelector('#time');
	startTimer(time, display);
};
</script>