<div class="message success countdown">For delivery on <span id="date"><?php echo $block->getDeliveryDate(); ?></span> order within the next <span id="time"><?php echo $block->getTimeRemaining(); ?></span> seconds!</div>

<script>
function startTimer(duration, display) {
	var timer = duration;
	setInterval(function () {
		//hours = parseInt(timer / 60, 10)
		//minutes = parseInt(timer / 60, 10)
		//seconds = parseInt(timer % 60, 10);

		//minutes = minutes < 10 ? "0" + minutes : minutes;
		//seconds = seconds < 10 ? "0" + seconds : seconds;
		time = new Date(timer * 1000).toISOString().substr(11, 8);
		//alert(time);
		display.textContent = time;
		
		if (--timer < 0) {
			timer = 86400;
			//date = document.getElementById('date').innerHTML.substring(document.getElementById('date').innerHTML.indexOf("/") + 1);
			//day = document.getElementById('date').innerHTML.substr(0, document.getElementById('date').innerHTML.indexOf('/'));
			//day = parseInt(day)+1;
			//if (day.length == 1) {
				//day = 0 + day;
			//}
			//newdate = day + "/" + date;
			//document.getElementById('date').innerHTML(newdate);
		}
	}, 1000);
}

window.onload = function () {
	var time = <?php echo $block->getTimeRemainingSeconds(); ?>,
		display = document.querySelector('#time');
	startTimer(time, display);
};
</script>